### ISSUE TITLE
Kubernetes dev overlay

### ISSUE THREAD

**Issue by iperezx** [waggle-sensor/waggle-beehive-v2#12]
Following the instructions in https://github.com/waggle-sensor/waggle-beehive-v2/blob/main/docs/installing-beehive-in-a-kubernetes-cluster.md

After step 2:
```
./create-credentials-for-beehive.sh
```

It generates `credentials/beehive.yaml`, but it's missing the following secrets:
```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-tls-secret
type: Opaque
data:
  cert.pem: 
  key.pem: 
---
apiVersion: v1
kind: Secret
metadata:
  name: upload-server-ssh-host-key
type: Opaque
data:
  ssh-host-key: 
  ssh-host-key.pub: 
  ssh-host-key-cert.pub: 
```

So step 3 will only create the first configmap and error for the first secret. 

Am I missing anything? 

I think you guys just copy and paste the content that is needed in the secrets, but it's not explicit in the docs.

Are you guys interested in adding to Beehive a dev overlay like I added to [BK](https://github.com/waggle-sensor/beekeeper/tree/main/kubernetes#development-environment)?
